services:
  jenkins:
    build:
      context: .
      dockerfile: configs/Dockerfile
      args:
        - PLUGINS_FILE=${PLUGINS_FILE:-configs/plugins.txt}
    container_name: mobile-cicd-jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/seeds:/var/jenkins_config/seeds
      - ./configs/templates:/var/jenkins_templates
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_config
    restart: unless-stopped
    mem_limit: 16g
    networks:
      - cicd-network

  android-builder:
    build:
      context: .
      dockerfile: configs/android-builder.Dockerfile
    container_name: android-builder
    volumes:
      - android_sdk:/opt/android-sdk
    restart: unless-stopped
    mem_limit: 16g
    networks:
      - cicd-network
    depends_on:
      - jenkins

  ios-builder:
    image: cimg/base:stable
    container_name: ios-builder
    volumes:
      - ./projects:/projects
    restart: unless-stopped
    mem_limit: 16g
    networks:
      - cicd-network
    command: tail -f /dev/null

  nexus:
    image: sonatype/nexus3
    container_name: mobile-nexus-repo
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    restart: unless-stopped
    mem_limit: 16g
    networks:
      - cicd-network

  sonarqube:
    image: sonarqube:community
    container_name: mobile-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JAVA_OPTS=-Xmx2048m -Xms512m
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    mem_limit: 16g
    networks:
      - cicd-network

volumes:
  jenkins_home:
  android_sdk:
  nexus-data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  cicd-network:
    driver: bridge
