services:
  jenkins:
    build: ./jenkins
    container_name: mobile-cicd-jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_config
    restart: unless-stopped
    networks:
      - cicd-network

  android-builder:
    image: thyrlian/android-sdk:latest
    container_name: android-builder
    volumes:
      - android_sdk:/opt/android-sdk
      - ./projects:/projects
    networks:
      - cicd-network
    command: tail -f /dev/null

  ios-builder:
    image: cimg/base:stable
    container_name: ios-builder
    volumes:
      - ./projects:/projects
    networks:
      - cicd-network
    command: tail -f /dev/null

  nexus:
    image: sonatype/nexus3
    container_name: mobile-nexus-repo
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - cicd-network
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cicd-network
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: mobile-sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - cicd-network
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096

volumes:
  jenkins_home:
  android_sdk:
  nexus-data:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  cicd-network:
    driver: bridge
    